### ISSUE TITLE
浏览器扩展 - 给 THBWiki 页面上的歌曲名称前增加一个链接到网易云对应曲子的按钮

### ISSUE THREAD

**Issue by Lionad-Morotar** [Lionad-Morotar/checheyun#2]
将浏览器扩展拆分为了一个新的项目。

见：https://github.com/Lionad-Morotar/thbwiki-enhance

**Comment by Lionad-Morotar** [comment]
另注：浏览器扩展项目的进度，仍通过本项目管理。

见：https://github.com/Lionad-Morotar/checheyun/projects/2

**Comment by Lionad-Morotar** [comment]
当前正在进行：

1. 给 THBWiki 页面上的歌曲名称前增加一个链接到网易云对应曲子的按钮。

**Comment by Lionad-Morotar** [comment]
在这个提交实现了：https://github.com/Lionad-Morotar/thbwiki-enhance/commit/68342a3de7212b1f7a2b1118949c34a7be0a89d8

![image](https://user-images.githubusercontent.com/26913795/88661110-90f3db00-d10a-11ea-87c2-0e9b7abcedc4.png)

测试插件请到 QQ 群下载，如果遇到问题，到这个页面提交问题报告：https://github.com/Lionad-Morotar/thbwiki-enhance/issues

**Comment by 1079105176** [comment]
去除搜索页面分区链接，只保留默认的网易云单曲搜索链接
![Uploading }FMT}2_6Q6_GZAKYA}4$AQV.png…]()

**Comment by 1079105176** [comment]
选取关键字后可以直接在关键词旁边显示网易云和wiki搜索页面的快捷图标

**Comment by Lionad-Morotar** [comment]
> 选取关键字后可以直接在关键词旁边显示网易云和wiki搜索页面的快捷图标，点击跳转

蛋黄，添加播放按钮这个需求上次搞定了，我先关闭了。然后你新提的这个功能，我另起了一个 Issue 维护，见：https://github.com/Lionad-Morotar/checheyun/issues/3
